name: remi
description: App for quick order tables in restaurants.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  firebase_auth:
  firebase_core:
  firebase_storage:
  firebase_database:
  google_sign_in:
  google_maps_flutter:
  location:
  geocoder_buddy:
  connectivity_plus:
  the_apple_sign_in:
  path_provider:
  http: 
  firebase_auth_oauth:
  flutter:
    sdk: flutter
  firebase_ui_database:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:   
    - assets/images/
    - assets/icons/

