name: remi
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  firebase_auth:
  firebase_core:
  google_sign_in:
  the_apple_sign_in:
  firebase_auth_oauth:
  provider:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:   
    - assets/images/
    - assets/icons/

