name: remi
description: App for quick order tables in restaurants.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  firebase_auth:
  firebase_core:
  google_sign_in:
  the_apple_sign_in:
  path_provider:
  shared_preferences:
  firebase_auth_oauth:
  flutter:
    sdk: flutter
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:   
    - assets/images/
    - assets/icons/

